name: Django CI Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      db: 
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: mytestrootpassword
          MYSQL_DATABASE: messaging_db
          MYSQL_USER: messaging_user
          MYSQL_PASSWORD: supersecurepassword_db
        ports:
          - 3306:3306

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies for MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev netcat

    - name: Install Python Dependencies
      working-directory: messaging_app
      run: pip3 install -r requirements.txt

    - name: Wait for MySQL Service to be ready
      run: |
        echo "Waiting for MySQL service to start on db:3306..."
        while ! nc -z db 3306; do
          sleep 1
        done
        echo "MySQL is up and running!"

    - name: Run Django Tests
      working-directory: messaging_app
      env:
        MYSQL_DB: messaging_db
        MYSQL_USER: messaging_user
        MYSQL_PASSWORD: supersecurepassword_db
        DB_HOST: db
        DB_PORT: 3306
        SECRET_KEY: django-insecure-test-key
        DJANGO_SETTINGS_MODULE: messaging_app.settings
      run: python manage.py test