# messaging_app/docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: messaging_app_db
    
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  web:
    build: .
    container_name: messaging_app_web
    
    command: python3 manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      
    env_file:
      - .env
      
    depends_on:
      - db
    restart: always

volumes:
  mysql_data: