apiVersion: v1
kind: Service
metadata:
  name: messaging-app-bg-service 
  labels:
    app: messaging-app-bg
spec:
  type: ClusterIP
  selector:
    app: messaging-app-bg
    color: blue 
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http-app
